using System;
using System.Windows.Forms;
namespace AminPhoneBook {
 public class ContactForm:Form {
  TextBox first,last,company,mobile,phone,mobile2,email,email2,address,group,tags,notes,reminder;DateTimePicker birthday,anniversary,nextReminder;CheckBox fav;public Contact Result{get;private set;}Contact original;
  public ContactForm(Contact c=null){original=c;Text=c==null?"مخاطب جدید":"ویرایش مخاطب";Width=780;Height=620;StartPosition=FormStartPosition.CenterParent;RightToLeft=RightToLeft.Yes;RightToLeftLayout=true;var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,RowCount=8,Padding=new Padding(12)};for(int i=0;i<4;i++)t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,25));first=F(t,"نام",0,0);last=F(t,"نام خانوادگی",1,0);company=F(t,"شرکت",2,0);mobile=F(t,"موبایل",3,0);phone=F(t,"تلفن",0,1);mobile2=F(t,"موبایل دوم",1,1);email=F(t,"ایمیل",2,1);email2=F(t,"ایمیل دوم",3,1);address=F(t,"آدرس",0,2,2);group=F(t,"گروه",2,2);tags=F(t,"برچسب‌ها",3,2);notes=F(t,"یادداشت",0,3,4);birthday=D(t,"تولد",0,4);anniversary=D(t,"سالگرد",1,4);fav=new CheckBox{Text="⭐ علاقه‌مندی",Dock=DockStyle.Fill};t.Controls.Add(fav,2,4);nextReminder=D(t,"یادآوری",0,5);reminder=F(t,"متن یادآوری",1,5,3);var save=new Button{Text="ذخیره",Dock=DockStyle.Fill};var cancel=new Button{Text="انصراف",Dock=DockStyle.Fill};t.Controls.Add(save,2,6);t.Controls.Add(cancel,3,6);Controls.Add(t);save.Click+=Save;cancel.Click+=(s,e)=>Close();if(c!=null)LoadContact(c);}
  TextBox F(TableLayoutPanel t,string label,int c,int r,int span=1){var p=new Panel{Dock=DockStyle.Fill};p.Controls.Add(new Label{Text=label,Dock=DockStyle.Top,Height=22});var b=new TextBox{Dock=DockStyle.Fill,RightToLeft=RightToLeft.Yes};p.Controls.Add(b);t.Controls.Add(p,c,r);if(span>1)t.SetColumnSpan(p,span);return b;}DateTimePicker D(TableLayoutPanel t,string label,int c,int r){var p=new Panel{Dock=DockStyle.Fill};p.Controls.Add(new Label{Text=label,Dock=DockStyle.Top,Height=22});var d=new DateTimePicker{Dock=DockStyle.Fill,Format=DateTimePickerFormat.Short,ShowCheckBox=true};p.Controls.Add(d);t.Controls.Add(p);return d;}
  void LoadContact(Contact c){first.Text=c.FirstName;last.Text=c.LastName;company.Text=c.Company;mobile.Text=c.Mobile;phone.Text=c.Phone;mobile2.Text=c.Mobile2;email.Text=c.Email;email2.Text=c.Email2;address.Text=c.Address;group.Text=c.Group;tags.Text=c.Tags;notes.Text=c.Notes;fav.Checked=c.Favorite;if(c.Birthday.HasValue){birthday.Checked=true;birthday.Value=c.Birthday.Value;}if(c.Anniversary.HasValue){anniversary.Checked=true;anniversary.Value=c.Anniversary.Value;}if(c.NextReminder.HasValue){nextReminder.Checked=true;nextReminder.Value=c.NextReminder.Value;}reminder.Text=c.ReminderText;}
  void Save(object s,EventArgs e){if(string.IsNullOrWhiteSpace(first.Text)&&string.IsNullOrWhiteSpace(last.Text)){MessageBox.Show("نام یا نام خانوادگی را وارد کنید.");return;}var c=original??new Contact();c.FirstName=first.Text.Trim();c.LastName=last.Text.Trim();c.Company=company.Text.Trim();c.Mobile=mobile.Text.Trim();c.Phone=phone.Text.Trim();c.Mobile2=mobile2.Text.Trim();c.Email=email.Text.Trim();c.Email2=email2.Text.Trim();c.Address=address.Text.Trim();c.Group=group.Text.Trim();c.Tags=tags.Text.Trim();c.Notes=notes.Text;c.Favorite=fav.Checked;c.Birthday=birthday.Checked?birthday.Value.Date:(DateTime?)null;c.Anniversary=anniversary.Checked?anniversary.Value.Date:(DateTime?)null;c.NextReminder=nextReminder.Checked?nextReminder.Value:(DateTime?)null;c.ReminderText=reminder.Text;c.UpdatedAt=DateTime.Now;Result=c;DialogResult=DialogResult.OK;Close();}
 }
}