using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;
namespace AminPhoneBook {
 public class MainForm:Form {
  CryptoStore store;PhoneBookData data;DataGridView grid;TextBox search;Label status;Timer reminderTimer;
  public MainForm(string password){store=new CryptoStore(password);try{data=store.Load();}catch(Exception ex){MessageBox.Show("باز کردن اطلاعات ممکن نشد:\r\n"+ex.Message);Environment.Exit(1);return;}Text="دفترچه تلفن حرفه‌ای";Width=1250;Height=760;MinimumSize=new Size(1000,600);StartPosition=FormStartPosition.CenterScreen;RightToLeft=RightToLeft.Yes;RightToLeftLayout=true;Build();reminderTimer=new Timer{Interval=60000};reminderTimer.Tick+=(s,e)=>CheckReminders();reminderTimer.Start();CheckReminders();}
  void Build(){var top=new Panel{Dock=DockStyle.Top,Height=58,Padding=new Padding(8)};search=new TextBox{Dock=DockStyle.Fill,Font=new Font("Tahoma",11)};top.Controls.Add(search);top.Controls.Add(new Label{Text="جستجوی همه فیلدها:",Dock=DockStyle.Right,Width=130,TextAlign=ContentAlignment.MiddleCenter});search.TextChanged+=(s,e)=>RefreshGrid();var menu=new MenuStrip{Dock=DockStyle.Top};var file=new ToolStripMenuItem("فایل");file.DropDownItems.Add("پشتیبان‌گیری",null,(s,e)=>Backup());file.DropDownItems.Add("بازیابی",null,(s,e)=>Restore());file.DropDownItems.Add("خروجی CSV",null,(s,e)=>ExportCsv());file.DropDownItems.Add("ورود CSV",null,(s,e)=>ImportCsv());file.DropDownItems.Add("خروج",null,(s,e)=>Close());var tools=new ToolStripMenuItem("ابزار");tools.DropDownItems.Add("مخاطبین تکراری",null,(s,e)=>Duplicates());tools.DropDownItems.Add("سطل زباله",null,(s,e)=>Trash());tools.DropDownItems.Add("یادآوری‌ها",null,(s,e)=>new ReminderForm(data).ShowDialog(this));tools.DropDownItems.Add("تنظیمات",null,(s,e)=>Settings());menu.Items.Add(file);menu.Items.Add(tools);Controls.Add(menu);var buttons=new FlowLayoutPanel{Dock=DockStyle.Left,Width=520,Height=55};var add=B("مخاطب جدید");var edit=B("ویرایش");var del=B("حذف");var fav=B("⭐ علاقه‌مندی");var all=B("همه");buttons.Controls.AddRange(new Control[]{add,edit,del,fav,all});top.Controls.Add(buttons);add.Click+=(s,e)=>Edit(null);edit.Click+=(s,e)=>Edit(Selected());del.Click+=(s,e)=>Delete();fav.Click+=(s,e)=>ToggleFav();all.Click+=(s,e)=>{search.Clear();data.Contacts.ForEach(x=>x.Deleted=false);RefreshGrid();};grid=new DataGridView{Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,AutoGenerateColumns=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,BackgroundColor=Color.White};Col("نام","FullName",190);Col("موبایل","Mobile",130);Col("تلفن","Phone",120);Col("شرکت","Company",150);Col("گروه","Group",110);Col("ایمیل","Email",190);Col("⭐","Favorite",45);grid.DoubleClick+=(s,e)=>Edit(Selected());grid.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.Delete)Delete();};status=new Label{Dock=DockStyle.Bottom,Height=28,TextAlign=ContentAlignment.MiddleRight};Controls.Add(grid);Controls.Add(status);Controls.Add(top);RefreshGrid();}
  Button B(string t){return new Button{Text=t,Width=95,Height=34,Margin=new Padding(3)};}void Col(string h,string p,int w){grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText=h,DataPropertyName=p,Width=w});}Contact Selected(){return grid.CurrentRow==null?null:grid.CurrentRow.DataBoundItem as Contact;}void RefreshGrid(){string q=search.Text.Trim();var a=data.Contacts.Where(c=>!c.Deleted&&(string.IsNullOrEmpty(q)||SearchIn(c,q))).OrderByDescending(c=>c.Favorite).ThenBy(c=>c.LastName).ThenBy(c=>c.FirstName).ToList();grid.DataSource=null;grid.DataSource=a;status.Text="تعداد مخاطبین: "+a.Count+"    |    علاقه‌مندی: "+data.Contacts.Count(x=>!x.Deleted&&x.Favorite);}
  bool SearchIn(Contact c,string q){string s=string.Join(" ",new[]{c.FirstName,c.LastName,c.Company,c.Mobile,c.Phone,c.Mobile2,c.Email,c.Email2,c.Address,c.Group,c.Tags,c.Notes});return s.IndexOf(q,StringComparison.CurrentCultureIgnoreCase)>=0;}void Edit(Contact c){using(var f=new ContactForm(c))if(f.ShowDialog(this)==DialogResult.OK){if(c==null)data.Contacts.Add(f.Result);store.Save(data);RefreshGrid();}}void Delete(){var c=Selected();if(c==null)return;if(data.Settings.ConfirmDelete&&MessageBox.Show("مخاطب به سطل زباله منتقل شود؟","تأیید",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;c.Deleted=true;c.UpdatedAt=DateTime.Now;store.Save(data);RefreshGrid();}void ToggleFav(){var c=Selected();if(c==null)return;c.Favorite=!c.Favorite;store.Save(data);RefreshGrid();}
  void Trash(){var x=data.Contacts.Where(c=>c.Deleted).OrderByDescending(c=>c.UpdatedAt).ToList();if(x.Count==0){MessageBox.Show("سطل زباله خالی است.");return;}var f=new Form{Text="سطل زباله",Width=700,Height=450,StartPosition=FormStartPosition.CenterParent,RightToLeft=RightToLeft.Yes,RightToLeftLayout=true};var l=new ListBox{Dock=DockStyle.Fill};foreach(var c in x)l.Items.Add(c.FullName+" | "+c.Mobile);var restore=new Button{Text="بازیابی",Dock=DockStyle.Bottom,Height=38};f.Controls.Add(l);f.Controls.Add(restore);restore.Click+=(s,e)=>{if(l.SelectedIndex>=0){x[l.SelectedIndex].Deleted=false;store.Save(data);f.Close();RefreshGrid();}};f.ShowDialog(this);}
  void Duplicates(){var groups=data.Contacts.Where(c=>!c.Deleted&&!string.IsNullOrWhiteSpace(c.Mobile)).GroupBy(c=>Normalize(c.Mobile)).Where(g=>g.Count()>1).ToList();if(groups.Count==0){MessageBox.Show("مورد تکراری پیدا نشد.");return;}MessageBox.Show(string.Join("\r\n",groups.Select(g=>"• "+string.Join("، ",g.Select(c=>c.FullName)))),"مخاطبین احتمالی تکراری");}string Normalize(string s){return new string((s??"").Where(char.IsDigit).ToArray()).TrimStart('0');}
  void Backup(){try{if(!store.Exists){MessageBox.Show("هنوز داده‌ای برای پشتیبان‌گیری وجود ندارد.");return;}MessageBox.Show("پشتیبان ساخته شد:\r\n"+store.MakeBackup());}catch(Exception ex){MessageBox.Show(ex.Message);}}void Restore(){using(var d=new OpenFileDialog{Filter="Encrypted Backup (*.apb)|*.apb"})if(d.ShowDialog()==DialogResult.OK){try{store.Restore(d.FileName);data=store.Load();RefreshGrid();MessageBox.Show("بازیابی انجام شد.");}catch(Exception ex){MessageBox.Show("بازیابی ناموفق:\r\n"+ex.Message);}}}
  void ExportCsv(){using(var d=new SaveFileDialog{Filter="CSV UTF-8 (*.csv)|*.csv",FileName="Contacts.csv"})if(d.ShowDialog()==DialogResult.OK){var sb=new StringBuilder();sb.AppendLine("FirstName,LastName,Company,Mobile,Phone,Mobile2,Email,Email2,Address,Group,Tags,Notes,Favorite");foreach(var c in data.Contacts.Where(x=>!x.Deleted))sb.AppendLine(string.Join(",",new[]{c.FirstName,c.LastName,c.Company,c.Mobile,c.Phone,c.Mobile2,c.Email,c.Email2,c.Address,c.Group,c.Tags,c.Notes,c.Favorite.ToString()}.Select(E)));File.WriteAllText(d.FileName,sb.ToString(),new UTF8Encoding(true));MessageBox.Show("خروجی ساخته شد.");}}
  void ImportCsv(){using(var d=new OpenFileDialog{Filter="CSV (*.csv)|*.csv"})if(d.ShowDialog()==DialogResult.OK){var lines=File.ReadAllLines(d.FileName,Encoding.UTF8);int n=0;foreach(var line in lines.Skip(1)){var a=ParseCsv(line);if(a.Count<5)continue;data.Contacts.Add(new Contact{FirstName=a[0],LastName=a[1],Company=a[2],Mobile=a[3],Phone=a[4],Email=a.Count>5?a[5]:""});n++;}store.Save(data);RefreshGrid();MessageBox.Show(n+" مخاطب وارد شد.");}}List<string> ParseCsv(string s){var r=new List<string>();var b=new StringBuilder();bool q=false;foreach(char c in s){if(c=='"'){q=!q;continue;}if(c==','&&!q){r.Add(b.ToString());b.Clear();}else b.Append(c);}r.Add(b.ToString());return r;}string E(string s){return "\"" +(s??"").Replace("\"","\"\"")+"\"";}
  void Settings(){using(var f=new SettingsForm(data.Settings))if(f.ShowDialog(this)==DialogResult.OK){store.Save(data);ApplyTheme();}}void ApplyTheme(){}void CheckReminders(){var now=DateTime.Now;foreach(var c in data.Contacts.Where(x=>!x.Deleted&&x.NextReminder.HasValue&&x.NextReminder.Value<=now&&x.NextReminder.Value>now.AddMinutes(-2)))MessageBox.Show("یادآوری برای "+c.FullName+"\r\n"+c.ReminderText,"یادآوری",MessageBoxButtons.OK,MessageBoxIcon.Information);}
 }
}